FROM node:13.12.0-alpine as build

WORKDIR /src/frontend

ENV PATH /src/frontend/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent

COPY . ./

RUN npm run build