version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  backend:
    build: ./app
    command: uwsgi --ini uwsgi.ini
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./app:/src/app
      - assets:/src/app/assets
      - media:/src/app/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery:
    build: ./app
    container_name: 'celery'
    command: celery -A store worker -B
    volumes:
      - .:/code
    links:
      - redis
    env_file:
      - ./.env.prod
    depends_on:
      - backend
      - redis
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/src/frontend
      - www:/src/frontend/build
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - www:/www
      - assets:/src/app/assets
      - media:/src/app/media
volumes:
  postgres_data:
  www:
  media:
  assets: