version: '3.7'
services:
  redis:
    expose: []
  db:
    environment: []
    env_file:
      - ./.env.prod.db
  backend:
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./app:/src/app
      - assets:/src/app/assets
      - media:/src/app/media
    env_file:
      - ./.env.prod
  celery:
    env_file:
      - ./.env.prod
  celery-beat:
    env_file:
      - ./.env.prod
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - assets:/src/app/assets
      - media:/src/app/media
      - front:/src/oldfrontend/build
volumes:
  postgres_data:
  media:
  assets:
  front: