version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: always
    container_name: 'redis'
    command: redis-server
    expose:
      - 6379
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_dev
  backend:
    build: ./app
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./app:/src/app
    ports:
      - 80:9000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  celery:
    build: ./app
    container_name: 'celery'
    command: watchmedo auto-restart --patterns "*.py" --recursive -- celery -A store worker -B
    volumes:
      - ./app:/src/app
    links:
      - redis
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - redis
  celery-beat:
    build: ./app
    command: celery -A store beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    links:
      - redis
    env_file:
      - ./.env.dev
    depends_on:
      - backend
      - redis
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/src/frontend'
      - 'node_modules:/src/frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
volumes:
  postgres_data:
  node_modules: