version: '3.7'
services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build: ./app
    command: uwsgi --ini uwsgi.ini
    ports:
      - 8000:8000
    volumes:
      - ./app:/src/app
      - assets:/src/app/assets
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery:
    build: ./app
    container_name: 'celery'
    command: celery -A store worker -B
    volumes:
      - .:/code
    links:
      - redis
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - assets:/src/app/assets
volumes:
  postgres_data:
  assets: