# Generated by Django 3.1 on 2020-08-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0015_order_delivery_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_id', models.IntegerField(db_index=True, verbose_name='ID в Яндекс.Доставке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Создана'), ('SHIPMENT_ORDERED', 'Заказана отгрузка'), ('IN_DELIVERY', 'В Яндекс.Доставке'), ('COMPLETED', 'Выполнена')], db_index=True, default='DRAFT', max_length=25, verbose_name='Статус доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ')),
            ],
        ),
    ]
