# Generated by Django 3.1 on 2020-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='yandex_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID в системе провайдера'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.CharField(choices=[('NONE', 'Отсутствует'), ('YANDEX_DELIVERY', 'Яндекс.Доставка')], db_index=True, default='NONE', max_length=20, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Запрошена'), ('DRAFT', 'Черновик'), ('CREATED', 'Создана'), ('SHIPMENT_ORDERED', 'Заказана отгрузка'), ('IN_DELIVERY', 'В доставке у провайдера'), ('COMPLETED', 'Выполнена')], db_index=True, default='REQUESTED', max_length=25, verbose_name='Статус доставки'),
        ),
    ]
