# Generated by Django 3.1 on 2020-09-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200911_2104'),
        ('delivery', '0006_auto_20200911_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_types', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
