# Generated by Django 3.1 on 2020-09-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20200912_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID в системе провайдера'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MANUAL', 'Самостоятельная доставка'), ('YANDEX', 'Яндекс.Доставка')], default='MANUAL', max_length=20, verbose_name='Провайдер')),
                ('date', models.DateField(verbose_name='Дата отгрузки')),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID в системе провайдера')),
                ('external_target_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID партнера назначения')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.warehouse', verbose_name='Склад')),
            ],
        ),
    ]
