# Generated by Django 3.1 on 2020-09-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200912_0826'),
        ('delivery', '0010_auto_20200918_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='Магазин'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
