# Generated by Django 3.1 on 2020-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20200918_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='act',
            field=models.FileField(blank=True, null=True, upload_to='acts', verbose_name='Акт передачи'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Запрошена'), ('SUBMITTED', 'Оформлена'), ('APPROVED', 'Подтверждена'), ('REPORTED', 'Репортирована складу'), ('COMPLETED', 'Выполнена')], db_index=True, default='REQUESTED', max_length=25, verbose_name='Статус отгрузки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Запрошена'), ('SUBMITTED', 'Оформлена'), ('APPROVED', 'Подтверждена'), ('IN_FULFILLMENT', 'Передана в фулфиллмент'), ('IN_DELIVERY', 'В доставке у провайдера'), ('COMPLETED', 'Выполнена'), ('ERROR', 'Ошибка'), ('CANCELED', 'Отменена')], db_index=True, default='REQUESTED', max_length=25, verbose_name='Статус доставки'),
        ),
    ]
