# Generated by Django 3.1 on 2020-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20200926_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Запрошена'), ('DRAFT', 'Черновик'), ('SUBMITTED', 'Оформлена'), ('APPROVED', 'Подтверждена'), ('REPORTED', 'Репортирована складу'), ('COMPLETED', 'Выполнена')], db_index=True, default='REQUESTED', max_length=25, verbose_name='Статус отгрузки'),
        ),
    ]
