# Generated by Django 3.1 on 2020-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20200926_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='added_price_fixed',
            field=models.PositiveIntegerField(default=0, verbose_name='Дополнительная стоимость в рублях'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='added_price_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Дополнительная стоимость в процентах'),
        ),
    ]
