# Generated by Django 3.1 on 2020-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20200928_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='end_time',
            field=models.TimeField(db_index=True, null=True, verbose_name='Время конца работы'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='start_time',
            field=models.TimeField(db_index=True, null=True, verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='deliveryproviderconfiguration',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Самостоятельная доставка'), ('YANDEX', 'Яндекс.Доставка'), ('DOSTAVISTA', 'Достависта')], default='MANUAL', max_length=20, verbose_name='Тип провайдера'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Самостоятельная доставка'), ('YANDEX', 'Яндекс.Доставка'), ('DOSTAVISTA', 'Достависта')], default='MANUAL', max_length=20, verbose_name='Тип провайдера'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Самостоятельная доставка'), ('YANDEX', 'Яндекс.Доставка'), ('DOSTAVISTA', 'Достависта')], default='MANUAL', max_length=20, verbose_name='Провайдер'),
        ),
    ]
