# Generated by Django 3.0.8 on 2020-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='items', verbose_name='Изображение'),
        ),
    ]
