# Generated by Django 3.1 on 2020-08-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('COURIER', 'Курьер'), ('POST', 'Почта')], default='NONE', max_length=7, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ'),
        ),
    ]
