# Generated by Django 3.1 on 2020-08-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_PAYMENT', 'Ожидает оплаты'), ('PAYED', 'Оплачен')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
