# Generated by Django 3.1 on 2020-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость товаров'),
        ),
    ]
