# Generated by Django 3.1 on 2020-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200819_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество на складе'),
        ),
    ]
