# Generated by Django 3.1 on 2020-08-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200819_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='payment_max_time',
            field=models.BooleanField(blank=True, null=True, verbose_name='Время на оплату заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_PAYMENT', 'Ожидает оплаты'), ('PAYED', 'Оплачен'), ('DELIVERY', 'В процессе доставки'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
