# Generated by Django 3.1 on 2020-08-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200825_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='payment_max_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на оплату заказа'),
        ),
    ]
