# Generated by Django 3.1 on 2020-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_delivery_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Партнер по доставке'),
        ),
    ]
