# Generated by Django 3.1 on 2020-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_delivery_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_option',
            new_name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_partner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_tariff',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительная информация о доставке'),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_provider',
            field=models.CharField(choices=[('NONE', 'Отсутствует'), ('YANDEX_DELIVERY', 'Яндекс.Доставка')], default='NONE', max_length=20, verbose_name='Провайдер доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='yandex_client_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID клиента Яндекс.Доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='yandex_dimensions',
            field=models.JSONField(blank=True, null=True, verbose_name='Габариты в Яндекс.Доставке'),
        ),
        migrations.AddField(
            model_name='shop',
            name='yandex_oauth_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='OAuth токен Яндекс.Доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='yandex_warehouse_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID склада Яндекс.Доставки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='yandex_warehouse_location',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес склада в Яндекс.Доставке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес покупателя'),
        ),
    ]
