# Generated by Django 3.1 on 2020-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200827_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='yandex_pickup_deadline',
            field=models.TimeField(blank=True, default='12:00', verbose_name='Дедлайн для отгрузки в текущий день'),
        ),
    ]
