# Generated by Django 3.1 on 2020-09-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200829_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='noreply_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочий email'),
        ),
        migrations.AddField(
            model_name='shop',
            name='noreply_email_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль рабочего email'),
        ),
    ]
