# Generated by Django 3.1 on 2020-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL-адрес магазина'),
        ),
    ]
