# Generated by Django 3.1 on 2020-09-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='warehouse_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email склада'),
        ),
    ]
