# Generated by Django 3.1 on 2020-09-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shop_warehouse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('COURIER', 'Курьер'), ('DIRECT_COURIER', 'Прямой курьер'), ('POST', 'Почта')], default='NONE', max_length=50, verbose_name='Способ доставки'),
        ),
    ]
