# Generated by Django 3.1 on 2020-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200911_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Способ доставки'),
        ),
    ]
