# Generated by Django 3.1 on 2020-09-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200912_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.order', verbose_name='Заказ'),
        ),
    ]
