# Generated by Django 3.1 on 2020-09-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200912_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='delivery_provider',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_client_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_dimensions',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_direct_addcost',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_oauth_token',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_pickup_deadline',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='yandex_warehouse_location',
        ),
    ]
